sudo: false
language: node_js
node_js:
 - '0.12'
before_script:
 - npm run build
env:
  global:
    - secure: cLTXBMC5WWHvnCpvDMdb3a7lBg/scjaFpjQoNu623YraVTnd66Es30IUeZNDZrAltmFNtoBZ1PRKdDl2OUWT3lKBK4pag9aGUBK630At2bPnAYNpMBSMaZhPRB+icAdb3Qan5Zmzr5yeKhx5uRXBfCeed1EmqyjzM9MSfHCAg2I=
    - secure: YKB10Gvn5qAWCcHfkuZ5bLGkg0D8gj4nCfgLUsbmeO5ANjkLgnXntTedvPozFmzhPn0hqI26JBycrhG4iS7IezrSlleVpmr3xpSmKNJGS6AP2nETyB2E2HxMwxpYNfgMU06o6gmfT5Ln+r2vebotSUbJ2loqwJ0E3eH8G0PKYFc=
addons:
  sauce_connect: true
